// <auto-generated />
using System;
using Habits.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Habits.Infrastructure.Migrations
{
    [DbContext(typeof(HabitsContext))]
    [Migration("20220921170846_InitHabits")]
    partial class InitHabits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("habits")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Habits.Domain.Entities.DailyProgress", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Value")
                        .HasColumnType("smallint");

                    b.HasKey("Date", "HabitId");

                    b.HasIndex("HabitId");

                    b.ToTable("DailyProgress", "habits");
                });

            modelBuilder.Entity("Habits.Domain.Entities.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("DailyGoal")
                        .HasColumnType("smallint");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Habits", "habits");
                });

            modelBuilder.Entity("Habits.Domain.Entities.Reminder", b =>
                {
                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Time", "HabitId");

                    b.HasIndex("HabitId");

                    b.ToTable("Reminder", "habits");
                });

            modelBuilder.Entity("Habits.Domain.Entities.DailyProgress", b =>
                {
                    b.HasOne("Habits.Domain.Entities.Habit", null)
                        .WithMany("Progress")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Habits.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("Habits.Domain.Entities.Habit", null)
                        .WithMany("Reminders")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Habits.Domain.Entities.Habit", b =>
                {
                    b.Navigation("Progress");

                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
